# DEV profile

# Datasource config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password:

## JPA CONFIG
spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.globally_quoted_identifiers: true
      # hibernate.hbm2ddl.import_files: /data/data-authors.sql

